theme: jekyll-theme-minimal
title: Joe Shenouda Github | Secure-Password-Generator

description: The Secure Password Generator is a lightweight, single-file Python script designed to create strong, random passwords that are resistant to brute-force attacks. It is a simple and effective tool for enhancing cybersecurity by promoting the use of secure passwords.

